site_name: CHEATS
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'Purple'
    accent: 'Purple'
  font:
    text: 'Ubuntu'
    code: 'Muli'
  favicon: assets/images/favicon.png

repo_name: GitHub
strict: true
extra:
  doc_owner: 'Vishnu Pradeep'
nav:
  - MY CHEATS: 'index.md'
  - CRYPTOGRAPHY:
    - Network Security: 'crypto/network_security.md'
    - SSL: 'crypto/ssl.md'
  - DOCKER:
    - Docker CA: 'docker/docker_ca.md'
  - GOLANG:
    - gomod: 'golang/gomod.md'
    - gotools: 'golang/go_tools.md'
  - NETWORKING: 'networking/networking.md'
  - WEB:
    - HTTP: 'web/http.md'
    - Nginx: 'web/nginx.md'