site_name: Cheats
repo_url: https://github.com/vishnu9304/cheats
site_description: Cheats for future reference
repo_name: GitHub
strict: true
theme: vzm-devguide
extra:
  doc_owner: Vishnu Pradeep
  doc_owner_shortid: 'vishnu930417@gmail.com'

nav:
- Cheats:
  - Welcome: 'index.md'
- Crypto:
  - network_security: 'crypto/network_security.md'
  - ssl: 'crypto/ssl.md'
- docker:
  - docker_ca: 'docker/docker_ca.md'